### PR TITLE
submission for review initial.

### PR DESCRIPTION
**Pull request by kmakai**
Good project. learned a lot from it.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kmakai This isn't a requirement but it will be potentially a good learning experience. When using datetime.parse it won't work in different cultures. Could you please modify that?

image


Check this out:  https://stackoverflow.com/questions/34355795/datetime-parse-not-working-c-sharp

**Comment by kmakai** [comment]
I see what you mean I changed it to ParseExact with same format with culture independence. please let me know if there's any other way I can improve it.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kmakai Looking great! There's just one missing requirement: 
image

It's up to you how you want to implement this, but It would be a great exercise to update the list on a keyUp event. That's a nice user experience.

**Comment by kmakai** [comment]
I was able to implement the search but it just manipulates the table rows with CSS hopefully that's not too bad, not sure if there's a better way.

**Comment by TheCSharpAcademy** [comment]
> I was able to implement the search but it just manipulates the table rows with CSS hopefully that's not too bad, not sure if there's a better way.

No dramas, good command of JS! 😁😁

**Comment by TheCSharpAcademy** [comment]
@kmakai have you submitted your portfolio/resume?

**Comment by kmakai** [comment]
> @kmakai have you submitted your portfolio/resume?

I have not I was thinking of going up to angular before I do either of those.

**Pull request merged**
