### PR TITLE
Project Done

### PR DESCRIPTION
**Pull request by Forser**
So, Project is finished or not.

No fancy frontend since that's is a weak point for me.
But all functions are there.
Including search and filtering.

Sample Data included in AppDbContext which are populated on ModelCreate.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Forser Hey there! Thanks for submitting, it's looking good, I really like the generic repository pattern. 😊

I'm having trouble adding a transaction though. I didn't want to troubleshoot it, but at first glance it looks like I need a record in the wallet table? 

image

**Comment by Forser** [comment]
Yeah, wallet is who the owner is off the Budget.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Forser When I first open the app, I can add a category without a problem. If I try to add a transaction I get a blank page. With a bit of debugging I found the error that I had sent you in the previous comment (foreign key with wallet table missing). To improve the user experience it would be better to have some error message telling the users what are expected from them to make it work.

Also, I can't see an option to add a wallet in the UI.

image

**Comment by Forser** [comment]
Greetings @TheCSharpAcademy, I have sorted it hopefully, it will popup a modal if a userwallet doesn't exist.

**Pull request merged**
