### PR TITLE
Completed Budget app 

### PR DESCRIPTION
**Pull request by Doc415**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 Hey there! The project is looking tidy. 👏🏻There's just one thing missing: 
image

This is actually an important item as it's widely used in web dev or I wouldn't be blocking the approval 😢

**Comment by Doc415** [comment]
> @Doc415 Hey there! The project is looking tidy. 👏🏻There's just one thing missing: image
> 
> This is actually an important item as it's widely used in web dev or I wouldn't be blocking the approval 😢

No problem .  I ll just go simple .

**Comment by Doc415** [comment]
Here we go 
One page to rule them all... :)

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Doc415 Hey! I'm glad you actually created a Budget project, not that I didn't like the radiology one.. 😆 But I don't think I was clear 😢, by modals I mean pop-up windows: 
image

You can implement them relatively easily with Bootstrap 5: https://getbootstrap.com/docs/5.0/components/modal/

**Comment by Doc415** [comment]
> @Doc415 Hey! I'm glad you actually created a Budget project, not that I didn't like the radiology one.. 😆 But I don't think I was clear 😢, by modals I mean pop-up windows: image
> 
> You can implement them relatively easily with Bootstrap 5: https://getbootstrap.com/docs/5.0/components/modal/

I am already using modals????

image

image

image




https://github.com/TheCSharpAcademy/CodeReviews.MVC.Budget/assets/94632226/0de9a332-451d-4c96-ab2f-a01f5e37d804



I have add and update transactions as hided html. Do it on purpose for nice looking UI. I can convert it to modal if necessary.

**Pull request closed without merging**
